### ISSUE TITLE
Response Content Type in Swagger

### ISSUE THREAD

**Issue by zuphilip** [infolis/infolis-web#21]
Using a non-standard option in the response content type (e.g. + `rdf+xml`) does not affect the `curl` action shown below or the `request headers`.

**Comment by kba** [comment]
Can you give an example? Apparently a problem like that just crashed the server, would like to reproduce.

**Comment by kba** [comment]
The bug happens for `text/n3`, must investigate in infolis/mongoose-jsonld

**Comment by zuphilip** [comment]
See #20 the example

**Comment by kba** [comment]
There was some confusion of media types across the rdf processing libraries. Should be fixed now.

**Comment by zuphilip** [comment]
Yes, now it works to choose a non-standard option in the response content type withouth a crash and the `response body` will change accordingly. 

The `response headers` and the options in the `curl` call are not yet fixed (see initial comment). Thus, I will leave that issue open but with low priority.

**Comment by kba** [comment]
It's a bug in Swagger. Updated the library to the latet version and it's the same error. It doesn't work for the bundled HTML app either (try: http://infolis.gesis.org/infolink/vendor/swagger-ui/dist/index.html). Not much we can do short of digging into the Swagger JS (the `Accept` header is also wrong).

The important thing is that the requests are sent to the server correctly.

**Comment by kba** [comment]
It doesn't work on the official demo site either: http://petstore.swagger.io/ with http://infolis.gesis.org/infolink/swagger.json

**Comment by zuphilip** [comment]
It is confirmed that this is a [swagger-ui bug](https://github.com/swagger-api/swagger-ui/issues/1767#event-469500980) and it was given the tag `P2`. I guess that means priority.

**Comment by kba** [comment]
Seems fixed upstream by https://github.com/swagger-api/swagger-ui/commit/8276fbf07373d8ec01eaf09941f7f6342ef2517a

**Comment by kba** [comment]
Yes, https://github.com/swagger-api/swagger-ui/issues/1767#event-469500980 is fixed and so is this.

**Comment by zuphilip** [comment]
Yes, I see that the `curl` command is now fine. Shouldn't the request header change as well? Cf.

![request-headers](https://cloud.githubusercontent.com/assets/5199995/11483909/71b99de4-97ab-11e5-8bf4-8d9b6ea87720.jpg)

**Comment by kba** [comment]
Yes they should :unamused:

**Comment by zuphilip** [comment]
Is that standard field in swagger-ui? I think I haven't seen this in the demo example from swagger-ui itself...

**Comment by kba** [comment]
Yes, it's a standard field, but it's disabled in the petstore demo. I disabled it here as well.
